USER_STATUS_NEW = 0
USER_STATUS_PROCESSED = 1
USER_STATUS_PROCESSING = 2
USER_STATUS_FAILED = 3

FOLLOWER_STATUS_NO = 0
FOLLOWER_STATUS_YES = 1
FOLLOWER_STATUS_OLD = 2
FOLLOWER_STATUS_NEW = 3

FOLLOWING_STATUS_NO = 0
FOLLOWING_STATUS_YES = 1
FOLLOWING_STATUS_OLD = 2
FOLLOWING_STATUS_NEW = 3
